# Services
---
apiVersion: v1
kind: Service
metadata:
  name: database-prometheus-exporter
  namespace: windows-vms
spec:
  selector:
    vm.kubevirt.io/name: database
  ports:
    - protocol: TCP
      port: 9104
      targetPort: 9104
      name: metrics
---
apiVersion: v1
kind: Service
metadata:
  name: winweb01-prometheus-exporter
  namespace: windows-vms
spec:
  selector:
    vm.kubevirt.io/name: winweb01
  ports:
    - protocol: TCP
      port: 9182
      targetPort: 9182
      name: metrics
---
apiVersion: v1
kind: Service
metadata:
  name: winweb02-prometheus-exporter
  namespace: windows-vms
spec:
  selector:
    vm.kubevirt.io/name: winweb02
  ports:
    - protocol: TCP
      port: 9182
      targetPort: 9182
      name: metrics
# Routes
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: database-prometheus-metrics
  namespace: windows-vms
spec:
  to:
    kind: Service
    name: database-prometheus-exporter
    weight: 100
  port:
    targetPort: metrics
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: winweb01-prometheus-metrics
  namespace: windows-vms
spec:
  to:
    kind: Service
    name: winweb01-prometheus-exporter
    weight: 100
  port:
    targetPort: metrics
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: winweb02-prometheus-metrics
  namespace: windows-vms
spec:
  to:
    kind: Service
    name: winweb02-prometheus-exporter
    weight: 100
  port:
    targetPort: metrics
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
