# Default values for loadmaker
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deployer:
  domain: REPLACEME-OPENSHIFT_DOMAIN
  apiUrl: https://api.cluster.opentlc.com:6443

ingressgatway_url_path: https://localhost

loadvm:
  namespace: vms-aap-day2
  route: vms
