# Default values for prometheus-exporter-configs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deployer:
  domain: REPLACEME-OPENSHIFT_DOMAIN
  apiUrl: https://api.cluster.opentlc.com:6443
