---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubevirt-ui-features
  namespace: {{ .Values.kubevirt_config.namespace }}
data:
  autocomputeCPULimitsEnabled: "false"
  autocomputeCPULimitsPreviewEnabled: "false"
  automaticSubscriptionActivationKey: ""
  automaticSubscriptionOrganizationId: ""
  disabledGuestSystemLogsAccess: "false"
  kubevirtApiserverProxy: "true"
  loadBalancerEnabled: "false"
  nodePortAddress: ""
  nodePortEnabled: "false"
{{- if .Values.kubevirt_config.tree_view }}
  treeViewFolders: 'true'
{{- end }}
{{- if .Values.kubevirt_config.tree_view_folders }}
  treeView: 'true'
{{- end }}
