# Default values for vms.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deployer:
  domain: REPLACEME-OPENSHIFT_DOMAIN
  apiUrl: https://api.cluster.opentlc.com:6443

ingressgatway_url_path: https://localhost

new_vms:
  imageUrl: "http://s3.us-east.cloud-object-storage.appdomain.cloud/roadshowocpvirt"
  dataVolumes:
  - name: database
    size: 16Gi
  - name: winweb01
    size: 90Gi
  - name: winweb02
    size: 90Gi
  loadtest:
    - namespace: windows-vms
      route: windows-vms
      requests_per_second: 2
    - namespace: mass-vms
      route: mass-vms
      requests_per_second: 2
  windowsVms:
    count: 1
    namespace: windows-vms
    create_route: true
    route: windows-vms
    runStrategy: "RerunOnFailure"
    evictionStrategy: "LiveMigrate"
    machineType: q35
    cluster_monitoring_label: "monitoring.rhobs: coo-stack" # empty disabled
  massVms:
    count: 10
    namespace: mass-vms
    create_route: true
    route: mass-vms
    runStrategy: "Manual"
    evictionStrategy: "LiveMigrate"
    machineType: q35
    cluster_monitoring_label: "" # empty disabled
