---
apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: loki
  namespace: { .Values.netobserv.namespace }
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  managementState: Managed
  size: 1x.extra-small
  storage:
    schemas:
      - effectiveDate: '2025-02-02'
        version: v13
    secret:
      name: loki-s3
      type: s3
    tls:
      caKey: service-ca.crt
      caName: openshift-service-ca.crt
  storageClassName: ocs-external-storagecluster-cephfs
  tenants:
    mode: openshift-network
