---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: loki-bucket-odf
  namespace: netobserv
spec:
  generateBucketName: loki-bucket-odf
  storageClassName: openshift-storage.noobaa.io
