# loop over the number of VMs
# to create services, routes and loadtest deployments
{{- $vmset := index .Values.new_vms "massVms" }}
{{- $max_vms := ( add ( int $vmset.count ) 1 ) }}
{{- range $vm_index := untilStep 1 ( int $max_vms ) 1 }}
---
apiVersion: v1
kind: Service
metadata:
  name: database-{{ $vm_index }}
  namespace: {{ $vmset.namespace }}
spec:
  selector:
    vm.kubevirt.io/name: database-{{ $vm_index }}
  ports:
  - protocol: TCP
    name: mysql
    port: 3306
    targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $vmset.route }}-{{ $vm_index }}
  namespace: {{ $vmset.namespace }}
spec:
  selector:
    env: {{ $vmset.route }}-{{ $vm_index }}
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 80
{{- if $vmset.create_route }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $vmset.route }}-{{ $vm_index }}
  namespace: {{ $vmset.namespace }}
spec:
  host: {{ $vmset.route }}-{{ $vm_index }}-{{ $vmset.namespace }}.{{ $.Values.deployer.domain }}
  path: /
  to:
    kind: Service
    name: {{ $vmset.route }}-{{ $vm_index }}
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
{{- end }}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: loadmaker-{{ $vm_index }}
  namespace: {{ $vmset.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadtest-{{ $vm_index }}
  template:
    metadata:
      labels:
        app: loadtest-{{ $vm_index }}
    spec:
      containers:
        - name: container
          image: quay.io/rhpds/loadtest
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: REQUESTS_PER_SECOND
              value: '{{ $vmset.loadtest.requests_per_second }}'
            - name: DURATION
              value: '10000'
            - name: URL
              value: 'https://{{ $vmset.route }}-{{ $vm_index }}-{{ $vmset.namespace }}.{{ $.Values.deployer.domain }}'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
{{- end }}
